version: "3"

services:
  app:
    image: gdrivesync
    container_name: gdrivesync
    environment:
      REMOTE_FOLDER_NAME: from_server
    volumes:
      - /mnt/d/Users/Matvei/Developer/Projects/GDriveSyncPython/folder_sync:/app/folder_sync:ro

    restart: "no"