services:
  gdrivesync:
    #platform: linux/amd64
    build: .
    image: siegfriedschmidt/gdrivesync
    container_name: gdrivesync
    environment:
      - LOCAL_FOLDER_PATH=/app/folder_sync
      - AUTH_KEY_PATH=/app/auth/key.json
      - REMOTE_FOLDER_NAME=from_server
    volumes:
      - ./folder_sync:/app/folder_sync:ro
      - ./auth:/app/auth:ro

    restart: "unless-stopped"