services:
  drive-sync:
    platform: linux/amd64
    build: .
    image: siegfriedschmidt/drive-sync
    container_name: drive-sync
    environment:
      - DRIVE_TYPE=SYNOLOGY
      - LOCAL_FOLDER=/app/folder_sync
      - REMOTE_FOLDER=/home/Test
      - AUTH_KEY_PATH=/app/auth/synology.json
      - CLEAR_DOWNLOADS=1
    volumes:
      - ./folder_sync:/app/folder_sync
      - ./auth:/app/auth:ro

    restart: "unless-stopped"