version: "3"

services:
  app:
    image: gdrivesync
    container_name: gdrivesync
    environment:
      REMOTE_FOLDER_NAME: defaultfoldername
    volumes:
      - /local/path/folder:/app/folder_sync:ro

    restart: unless-stopped